In [2]:
for i in range(2,10): # 2~9단까지 => 출력 값이 2단부터이며, 첫 시작이 2 * 2이기에 초기값 수정
    for j in range(2,10): # 각 구구단은 2부터 9까지
        print( i,"*",j,"=",i*j) # 값 출력
    print("********************") # 해당 단이 끝나면 구분선

2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
********************
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
********************
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
********************
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
********************
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
********************
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
********************
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
********************
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
********************

In [3]:
for i in range(1,10): # 총 9줄
    for j in range(i,10): # 각 열에 찍힐 수 -> 거꾸로 출력하기 위해
        print( "*",end="")
    print(end="\n") # 해당 줄에 별을 모두 찍으면 줄바꿈

*********
********
*******
******
*****
****
***
**
*

In [4]:
i=1 # 열 카운터 변수
while True: # 무한루프
    j=i # 별 갯수 카운터 변수
    while True: # 무한루프
        if(j==10): break # 거꾸로 출력하기 위해 기준값 도달시 두번째 무한루프 탈출
        print( "*",end="") # 별찍기
        j+=1 # 카운터 변수 증가
    if(i==10): break # 목표 줄 도달시 첫번째 무한루프 탈출
    print(end="\n") # 별을 다 찍었으니 줄바꿈
    i+=1 # 다음줄로 카운터 변수 증가

*********
********
*******
******
*****
****
***
**
*

In [7]:
Mon=1
for date in [31,28,31,30,31,30,31,31,30,31,30,31]: # 마지막 날짜들을 넣은 컬랙션으로 for문
    print(Mon,"월 :",end="") # 해당 월 출력
    for Day in range(1,date+1): # 날짜의 나열
        if(Day==date): print(Day, end="\n") # 마지막 날짜에는 , 출력 안하고 줄바꿈 입력
        else: print(Day,end=",") # 줄줄이 날짜 출력
    Mon+=1 # 달 하나 증가

1 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
2 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
3 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
4 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
5 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
6 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
7 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
8 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
9 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
10 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
11 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
12 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31

In [8]:
for i in range(2,10,3): # 한줄에 3개씩 출력하기 위해 증가는 +3씩, 2단부터 시작
    for j in range(2,10):
        print(i,"*",j,"=",i*j,end="\t") # 첫번째줄 -> 2, 5, 8단
        print(i+1,"*",j,"=",i*j,end="\t") # 두번째줄 -> 3, 6, 9단
        if(i+2!=10): print(i+2,"*",j,"=",i*j,end="\n") # 세번째줄 -> 4, 7단 => 10단이 아닐경우에만 출력
        else: print(end="\n") # 10단 출력 자리일경우? 줄바꿈으로 출력 X
    print(end="\n") # 해당 줄의 단들이 출력 종료후, 한칸띄우기!

2 * 2 = 4	3 * 2 = 4	4 * 2 = 4
2 * 3 = 6	3 * 3 = 6	4 * 3 = 6
2 * 4 = 8	3 * 4 = 8	4 * 4 = 8
2 * 5 = 10	3 * 5 = 10	4 * 5 = 10
2 * 6 = 12	3 * 6 = 12	4 * 6 = 12
2 * 7 = 14	3 * 7 = 14	4 * 7 = 14
2 * 8 = 16	3 * 8 = 16	4 * 8 = 16
2 * 9 = 18	3 * 9 = 18	4 * 9 = 18

5 * 2 = 10	6 * 2 = 10	7 * 2 = 10
5 * 3 = 15	6 * 3 = 15	7 * 3 = 15
5 * 4 = 20	6 * 4 = 20	7 * 4 = 20
5 * 5 = 25	6 * 5 = 25	7 * 5 = 25
5 * 6 = 30	6 * 6 = 30	7 * 6 = 30
5 * 7 = 35	6 * 7 = 35	7 * 7 = 35
5 * 8 = 40	6 * 8 = 40	7 * 8 = 40
5 * 9 = 45	6 * 9 = 45	7 * 9 = 45

8 * 2 = 16	9 * 2 = 16
8 * 3 = 24	9 * 3 = 24
8 * 4 = 32	9 * 4 = 32
8 * 5 = 40	9 * 5 = 40
8 * 6 = 48	9 * 6 = 48
8 * 7 = 56	9 * 7 = 56
8 * 8 = 64	9 * 8 = 64
8 * 9 = 72	9 * 9 = 72

In [9]:
for i in range(2,10,3): # 한줄에 3개씩 출력하기 위해 증가는 +3씩, 2단부터 시작
    for j in range(2,10):
        print(i,"*",j,"=",i*j,end="\t") # 첫번째줄 -> 2, 3, 4단
        print(i+1,"*",j,"=",i*j,end="\t") # 두번째줄 -> 5, 6, 7단
        if(i+2!=10): print(i+2,"*",j,"=",i*j,end="\n") # 세번째줄 -> 8, 9단 => 10단이 아닐경우에만 출력
        else: print(end="\n") # 10단 출력 자리일경우? 줄바꿈으로 출력 X
    print(end="\n") # 해당 줄의 단들이 출력 종료후, 한칸띄우기!

2 * 2 = 4	3 * 2 = 4	4 * 2 = 4
2 * 3 = 6	3 * 3 = 6	4 * 3 = 6
2 * 4 = 8	3 * 4 = 8	4 * 4 = 8
2 * 5 = 10	3 * 5 = 10	4 * 5 = 10
2 * 6 = 12	3 * 6 = 12	4 * 6 = 12
2 * 7 = 14	3 * 7 = 14	4 * 7 = 14
2 * 8 = 16	3 * 8 = 16	4 * 8 = 16
2 * 9 = 18	3 * 9 = 18	4 * 9 = 18

5 * 2 = 10	6 * 2 = 10	7 * 2 = 10
5 * 3 = 15	6 * 3 = 15	7 * 3 = 15
5 * 4 = 20	6 * 4 = 20	7 * 4 = 20
5 * 5 = 25	6 * 5 = 25	7 * 5 = 25
5 * 6 = 30	6 * 6 = 30	7 * 6 = 30
5 * 7 = 35	6 * 7 = 35	7 * 7 = 35
5 * 8 = 40	6 * 8 = 40	7 * 8 = 40
5 * 9 = 45	6 * 9 = 45	7 * 9 = 45

8 * 2 = 16	9 * 2 = 16
8 * 3 = 24	9 * 3 = 24
8 * 4 = 32	9 * 4 = 32
8 * 5 = 40	9 * 5 = 40
8 * 6 = 48	9 * 6 = 48
8 * 7 = 56	9 * 7 = 56
8 * 8 = 64	9 * 8 = 64
8 * 9 = 72	9 * 9 = 72