In [1]:
f=0
try:
    f=open("LICENSE.txt","rt")
    while True:
        r=f.readline()
        if not r:
            break
        print(r)
except FileNotFoundError:
    print("파일없음")
finally:
    if(f): f.close()
    print("프로그램 끝")

파일없음
프로그램 끝

In [7]:
import random as r

f=0
f=open("score.txt","wt")
for i in range(100):
# 아래와 같은 형태를 만들기 위하여 str.format 함수를 사용할 수 있음
# one_person = "{0:s},{1:d},{2:d},{3:d}\n“
# .format("홍길동" + str(i), r.randrange(0,100), r.randrange(0,100), r.randrange(0,100))

    one_person="홍길동"+str(i)+","+str(r.randrange(0,100))+","+str(r.randrange(0,100))+","
    +str(r.randrange(0,100))+"\n"
    f.write(one_person) #한 줄씩 쓴다
    print(one_person)
f.close()

홍길동0,4,81,84

홍길동1,20,35,82

홍길동2,9,77,94

홍길동3,32,48,32

홍길동4,4,49,19

홍길동5,78,9,54

홍길동6,41,16,84

홍길동7,77,6,47

홍길동8,67,70,51

홍길동9,87,18,36

홍길동10,94,7,11

홍길동11,67,8,42

홍길동12,31,37,44

홍길동13,17,38,16

홍길동14,54,11,47

홍길동15,12,53,35

홍길동16,63,62,64

홍길동17,58,5,5

홍길동18,22,53,40

홍길동19,92,14,33

홍길동20,90,41,24

홍길동21,15,89,67

홍길동22,38,66,65

홍길동23,81,38,73

홍길동24,21,60,53

홍길동25,72,62,74

홍길동26,51,63,36

홍길동27,53,94,57

홍길동28,64,32,83

홍길동29,36,67,84

홍길동30,92,65,70

홍길동31,2,28,31

홍길동32,86,73,95

홍길동33,2,73,4

홍길동34,21,30,14

홍길동35,37,25,31

홍길동36,6,78,83

홍길동37,64,63,89

홍길동38,76,13,44

홍길동39,90,4,60

홍길동40,12,53,90

홍길동41,60,65,13

홍길동42,38,96,87

홍길동43,1,21,22

홍길동44,26,58,17

홍길동45,82,76,10

홍길동46,2,66,90

홍길동47,24,37,84

홍길동48,58,15,79

홍길동49,39,58,34

홍길동50,91,94,72

홍길동51,13,7,90

홍길동52,53,7,81

홍길동53,76,85,30

홍길동54,46,17,51

홍길동55,41,72,65

홍길동56,5,86,37

홍길동57,25,42,96

홍길동58,58,18,50

홍길동59,77,61,72

홍길동60,82,65,4

홍길동61,87,4,22

홍길동62,27,51,27

홍길동63,71,77,0

홍길동64,9,96,40

홍길동65,80,46,90

홍길동66,10,41,26

홍길동67,15,35,7

홍길동68,45,73,25

홍길동69,63,9,15

홍길동70,88,49,3

홍길동71,97,51,31

홍길동72,57,59,83

홍길동73,3,37,94

홍길동74,95,85,73

홍길동75,29,3,3

홍길동76,32,2,11

홍길동77,24,50,34

홍길동78,2,9,2

홍길동79,86,25,21

홍길동80,65,72,18

홍길동81,58,37,84

홍길동82,96,24,18

홍길동83,1,91,22

홍길동84,54,44,76

홍길동85,4,89,15

홍길동86,68,96,95

홍길동87,30,3,56

홍길동88,5,0,36

홍길동89,13,11,6

홍길동90,57,50,80

홍길동91,2,12,52

홍길동92,85,84,20

홍길동93,75,21,63

홍길동94,60,19,19

홍길동95,27,81,68

홍길동96,3,51,95

홍길동97,58,53,93

홍길동98,16,8,24

홍길동99,88,47,70

In [8]:
f=0
f=open("score.txt","rt")

while True:
    one_person=f.readline() # 한 줄씩 읽기
    if not one_person: break # 읽을 내용이 없으면 루프탈출
    one_person=one_person.replace("\n","") # 줄 바꿈문자 제거
    item=one_person.split(",") # 콤마 구분자로 분리
    print("="*10)
    print("이름: ", item[0])
    print("국어: ", item[1])
    print("영어: ", item[2])
    print("수학: ", item[3])
    print("="*10)
f.close()

==========
이름:  홍길동0
국어:  4
영어:  81
수학:  84
==========
==========
이름:  홍길동1
국어:  20
영어:  35
수학:  82
==========
==========
이름:  홍길동2
국어:  9
영어:  77
수학:  94
==========
==========
이름:  홍길동3
국어:  32
영어:  48
수학:  32
==========
==========
이름:  홍길동4
국어:  4
영어:  49
수학:  19
==========
==========
이름:  홍길동5
국어:  78
영어:  9
수학:  54
==========
==========
이름:  홍길동6
국어:  41
영어:  16
수학:  84
==========
==========
이름:  홍길동7
국어:  77
영어:  6
수학:  47
==========
==========
이름:  홍길동8
국어:  67
영어:  70
수학:  51
==========
==========
이름:  홍길동9
국어:  87
영어:  18
수학:  36
==========
==========
이름:  홍길동10
국어:  94
영어:  7
수학:  11
==========
==========
이름:  홍길동11
국어:  67
영어:  8
수학:  42
==========
==========
이름:  홍길동12
국어:  31
영어:  37
수학:  44
==========
==========
이름:  홍길동13
국어:  17
영어:  38
수학:  16
==========
==========
이름:  홍길동14
국어:  54
영어:  11
수학:  47
==========
==========
이름:  홍길동15
국어:  12
영어:  53
수학:  35
==========
==========
이름:  홍길동16
국어:  63
영어:  62
수학:  64
==========
==========
이름:  홍길동17
국어:  58
영어:  5
수학:  5
==========
==========
이름:  홍길동18
국어:  22
영어:  53
수학:  40
==========
==========
이름:  홍길동19
국어:  92
영어:  14
수학:  33
==========
==========
이름:  홍길동20
국어:  90
영어:  41
수학:  24
==========
==========
이름:  홍길동21
국어:  15
영어:  89
수학:  67
==========
==========
이름:  홍길동22
국어:  38
영어:  66
수학:  65
==========
==========
이름:  홍길동23
국어:  81
영어:  38
수학:  73
==========
==========
이름:  홍길동24
국어:  21
영어:  60
수학:  53
==========
==========
이름:  홍길동25
국어:  72
영어:  62
수학:  74
==========
==========
이름:  홍길동26
국어:  51
영어:  63
수학:  36
==========
==========
이름:  홍길동27
국어:  53
영어:  94
수학:  57
==========
==========
이름:  홍길동28
국어:  64
영어:  32
수학:  83
==========
==========
이름:  홍길동29
국어:  36
영어:  67
수학:  84
==========
==========
이름:  홍길동30
국어:  92
영어:  65
수학:  70
==========
==========
이름:  홍길동31
국어:  2
영어:  28
수학:  31
==========
==========
이름:  홍길동32
국어:  86
영어:  73
수학:  95
==========
==========
이름:  홍길동33
국어:  2
영어:  73
수학:  4
==========
==========
이름:  홍길동34
국어:  21
영어:  30
수학:  14
==========
==========
이름:  홍길동35
국어:  37
영어:  25
수학:  31
==========
==========
이름:  홍길동36
국어:  6
영어:  78
수학:  83
==========
==========
이름:  홍길동37
국어:  64
영어:  63
수학:  89
==========
==========
이름:  홍길동38
국어:  76
영어:  13
수학:  44
==========
==========
이름:  홍길동39
국어:  90
영어:  4
수학:  60
==========
==========
이름:  홍길동40
국어:  12
영어:  53
수학:  90
==========
==========
이름:  홍길동41
국어:  60
영어:  65
수학:  13
==========
==========
이름:  홍길동42
국어:  38
영어:  96
수학:  87
==========
==========
이름:  홍길동43
국어:  1
영어:  21
수학:  22
==========
==========
이름:  홍길동44
국어:  26
영어:  58
수학:  17
==========
==========
이름:  홍길동45
국어:  82
영어:  76
수학:  10
==========
==========
이름:  홍길동46
국어:  2
영어:  66
수학:  90
==========
==========
이름:  홍길동47
국어:  24
영어:  37
수학:  84
==========
==========
이름:  홍길동48
국어:  58
영어:  15
수학:  79
==========
==========
이름:  홍길동49
국어:  39
영어:  58
수학:  34
==========
==========
이름:  홍길동50
국어:  91
영어:  94
수학:  72
==========
==========
이름:  홍길동51
국어:  13
영어:  7
수학:  90
==========
==========
이름:  홍길동52
국어:  53
영어:  7
수학:  81
==========
==========
이름:  홍길동53
국어:  76
영어:  85
수학:  30
==========
==========
이름:  홍길동54
국어:  46
영어:  17
수학:  51
==========
==========
이름:  홍길동55
국어:  41
영어:  72
수학:  65
==========
==========
이름:  홍길동56
국어:  5
영어:  86
수학:  37
==========
==========
이름:  홍길동57
국어:  25
영어:  42
수학:  96
==========
==========
이름:  홍길동58
국어:  58
영어:  18
수학:  50
==========
==========
이름:  홍길동59
국어:  77
영어:  61
수학:  72
==========
==========
이름:  홍길동60
국어:  82
영어:  65
수학:  4
==========
==========
이름:  홍길동61
국어:  87
영어:  4
수학:  22
==========
==========
이름:  홍길동62
국어:  27
영어:  51
수학:  27
==========
==========
이름:  홍길동63
국어:  71
영어:  77
수학:  0
==========
==========
이름:  홍길동64
국어:  9
영어:  96
수학:  40
==========
==========
이름:  홍길동65
국어:  80
영어:  46
수학:  90
==========
==========
이름:  홍길동66
국어:  10
영어:  41
수학:  26
==========
==========
이름:  홍길동67
국어:  15
영어:  35
수학:  7
==========
==========
이름:  홍길동68
국어:  45
영어:  73
수학:  25
==========
==========
이름:  홍길동69
국어:  63
영어:  9
수학:  15
==========
==========
이름:  홍길동70
국어:  88
영어:  49
수학:  3
==========
==========
이름:  홍길동71
국어:  97
영어:  51
수학:  31
==========
==========
이름:  홍길동72
국어:  57
영어:  59
수학:  83
==========
==========
이름:  홍길동73
국어:  3
영어:  37
수학:  94
==========
==========
이름:  홍길동74
국어:  95
영어:  85
수학:  73
==========
==========
이름:  홍길동75
국어:  29
영어:  3
수학:  3
==========
==========
이름:  홍길동76
국어:  32
영어:  2
수학:  11
==========
==========
이름:  홍길동77
국어:  24
영어:  50
수학:  34
==========
==========
이름:  홍길동78
국어:  2
영어:  9
수학:  2
==========
==========
이름:  홍길동79
국어:  86
영어:  25
수학:  21
==========
==========
이름:  홍길동80
국어:  65
영어:  72
수학:  18
==========
==========
이름:  홍길동81
국어:  58
영어:  37
수학:  84
==========
==========
이름:  홍길동82
국어:  96
영어:  24
수학:  18
==========
==========
이름:  홍길동83
국어:  1
영어:  91
수학:  22
==========
==========
이름:  홍길동84
국어:  54
영어:  44
수학:  76
==========
==========
이름:  홍길동85
국어:  4
영어:  89
수학:  15
==========
==========
이름:  홍길동86
국어:  68
영어:  96
수학:  95
==========
==========
이름:  홍길동87
국어:  30
영어:  3
수학:  56
==========
==========
이름:  홍길동88
국어:  5
영어:  0
수학:  36
==========
==========
이름:  홍길동89
국어:  13
영어:  11
수학:  6
==========
==========
이름:  홍길동90
국어:  57
영어:  50
수학:  80
==========
==========
이름:  홍길동91
국어:  2
영어:  12
수학:  52
==========
==========
이름:  홍길동92
국어:  85
영어:  84
수학:  20
==========
==========
이름:  홍길동93
국어:  75
영어:  21
수학:  63
==========
==========
이름:  홍길동94
국어:  60
영어:  19
수학:  19
==========
==========
이름:  홍길동95
국어:  27
영어:  81
수학:  68
==========
==========
이름:  홍길동96
국어:  3
영어:  51
수학:  95
==========
==========
이름:  홍길동97
국어:  58
영어:  53
수학:  93
==========
==========
이름:  홍길동98
국어:  16
영어:  8
수학:  24
==========
==========
이름:  홍길동99
국어:  88
영어:  47
수학:  70
==========